local enum
enum = require("magick.enum").enum
  
local composite_operators = enum({
  [0] = "UndefinedCompositeOp",
  "AlphaCompositeOp",
  "AtopCompositeOp",
  "BlendCompositeOp",
  "BlurCompositeOp",
  "BumpmapCompositeOp",
  "ChangeMaskCompositeOp",
  "ClearCompositeOp",
  "ColorBurnCompositeOp",
  "ColorDodgeCompositeOp",
  "ColorizeCompositeOp",
  "CopyBlackCompositeOp",
  "CopyBlueCompositeOp",
  "CopyCompositeOp",
  "CopyCyanCompositeOp",
  "CopyGreenCompositeOp",
  "CopyMagentaCompositeOp",
  "CopyAlphaCompositeOp",
  "CopyRedCompositeOp",
  "CopyYellowCompositeOp",
  "DarkenCompositeOp",
  "DarkenIntensityCompositeOp",
  "DifferenceCompositeOp",
  "DisplaceCompositeOp",
  "DissolveCompositeOp",
  "DistortCompositeOp",
  "DivideDstCompositeOp",
  "DivideSrcCompositeOp",
  "DstAtopCompositeOp",
  "DstCompositeOp",
  "DstInCompositeOp",
  "DstOutCompositeOp",
  "DstOverCompositeOp",
  "ExclusionCompositeOp",
  "HardLightCompositeOp",
  "HardMixCompositeOp",
  "HueCompositeOp",
  "InCompositeOp",
  "IntensityCompositeOp",
  "LightenCompositeOp",
  "LightenIntensityCompositeOp",
  "LinearBurnCompositeOp",
  "LinearDodgeCompositeOp",
  "LinearLightCompositeOp",
  "LuminizeCompositeOp",
  "MathematicsCompositeOp",
  "MinusDstCompositeOp",
  "MinusSrcCompositeOp",
  "ModulateCompositeOp",
  "ModulusAddCompositeOp",
  "ModulusSubtractCompositeOp",
  "MultiplyCompositeOp",
  "NoCompositeOp",
  "OutCompositeOp",
  "OverCompositeOp",
  "OverlayCompositeOp",
  "PegtopLightCompositeOp",
  "PinLightCompositeOp",
  "PlusCompositeOp",
  "ReplaceCompositeOp",
  "SaturateCompositeOp",
  "ScreenCompositeOp",
  "SoftLightCompositeOp",
  "SrcAtopCompositeOp",
  "SrcCompositeOp",
  "SrcInCompositeOp",
  "SrcOutCompositeOp",
  "SrcOverCompositeOp",
  "ThresholdCompositeOp",
  "VividLightCompositeOp",
  "XorCompositeOp"
})
local gravity = enum({
  [0] = "ForgetGravity",
  "NorthWestGravity",
  "NorthGravity",
  "NorthEastGravity",
  "WestGravity",
  "CenterGravity",
  "EastGravity",
  "SouthWestGravity",
  "SouthGravity",
  "SouthEastGravity",
  "StaticGravity"
})
local orientation = enum({
  [0] = "UndefinedOrientation",
  "TopLeftOrientation",
  "TopRightOrientation",
  "BottomRightOrientation",
  "BottomLeftOrientation",
  "LeftTopOrientation",
  "RightTopOrientation",
  "RightBottomOrientation",
  "LeftBottomOrientation"
})
local interlace = enum({
  [0] = "UndefinedInterlace",
  "NoInterlace",
  "LineInterlace",
  "PlaneInterlace",
  "PartitionInterlace",
  "GIFInterlace",
  "JPEGInterlace",
  "PNGInterlace"
})
return {
  composite_operators = composite_operators,
  gravity = gravity,
  orientation = orientation,
  interlace = interlace
}
